# frozen_string_literal: true

# #Airthings API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.0
#

require "spec_helper"
require "json"

# Unit tests for Airthings::DevicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "DevicesApi" do
  before do
    # run before each test
    @api_instance = Airthings::DevicesApi.new
  end

  describe "test an instance of DevicesApi" do
    it "creates an instance of DevicesApi" do
      expect(@api_instance).to be_instance_of(Airthings::DevicesApi)
    end
  end

  # unit tests for device_info
  # Get info about a specific Device
  # @param serial_number
  # @param [Hash] opts the optional parameters
  # @option opts [String] :organization_id
  # @option opts [String] :user_group_id
  # @return [GetDeviceDetailedResponse]
  describe "device_info test" do
    it "works" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for device_samples_latest_values
  # Get latest Samples belonging to a specific Device (latest segment)
  # @param serial_number
  # @param [Hash] opts the optional parameters
  # @option opts [String] :organization_id
  # @option opts [String] :user_group_id
  # @return [SingleSampleResponse]
  describe "device_samples_latest_values test" do
    it "works" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for devices_list
  # Get Devices belonging to the Account
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :show_inactive
  # @option opts [String] :organization_id
  # @option opts [String] :user_group_id
  # @return [GetDevicesResponse]
  describe "devices_list test" do
    it "works" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
