# frozen_string_literal: true

# #Airthings API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.0
#

require "spec_helper"
require "json"

# Unit tests for Airthings::LocationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "LocationsApi" do
  before do
    # run before each test
    @api_instance = Airthings::LocationsApi.new
  end

  describe "test an instance of LocationsApi" do
    it "creates an instance of LocationsApi" do
      expect(@api_instance).to be_instance_of(Airthings::LocationsApi)
    end
  end

  # unit tests for location_info
  # Get info about a specific Location
  # @param location_id
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :show_inactive
  # @option opts [String] :organization_id
  # @option opts [String] :user_group_id
  # @return [GetLocationResponse]
  describe "location_info test" do
    it "works" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for locations_list
  # Get all added Locations
  # @param [Hash] opts the optional parameters
  # @option opts [String] :organization_id
  # @option opts [String] :user_group_id
  # @return [GetLocationsResponse]
  describe "locations_list test" do
    it "works" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
