# frozen_string_literal: true

# #Airthings API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for Airthings::LocationSimpleResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Airthings::LocationSimpleResponse do
  let(:instance) { described_class.new }

  describe "test an instance of LocationSimpleResponse" do
    it "creates an instance of LocationSimpleResponse" do
      expect(instance).to be_instance_of(described_class)
    end
  end

  describe 'test attribute "id"' do
    it "works" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it "works" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
